<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C0K1LII" failures="1" tests="3" name="Test" time="28.031" errors="0" timestamp="2022-07-27T14:31:41 IST">
  <testcase classname="TestClasses.VerifyUserCanLogIn" name="verifyUserCanLogin" time="3.95"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="verifyUserCanGoToProfilePage" time="3.034"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="veryUserCanAddAddress" time="4.514">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at TestClasses.VerifyUserCanAddNewAddress.veryUserCanAddAddress(VerifyUserCanAddNewAddress.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- veryUserCanAddAddress -->
</testsuite> <!-- Test -->
